#Server port :
server.port= 8812

#Application name :
spring.application.name= product-recommendation-service

#Client registration properties :
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

#Data source :
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/recommendation_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

#Jpa/Hibernate :
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [%X{correlationId}] - %msg%n

# Redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

# Kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Resilience4j Retry
resilience4j.retry.instances.productClient.maxAttempts=3
resilience4j.retry.instances.productClient.waitDuration=2s
resilience4j.retry.instances.productClient.retryExceptions[0]=java.util.concurrent.TimeoutException
resilience4j.retry.instances.productClient.retryExceptions[1]=java.net.ConnectException
resilience4j.retry.instances.productClient.retryExceptions[2]=feign.RetryableException

server.error.include-stacktrace=never
